name: form_builder_extra_fields
description: Additional ready-made form input fields for flutter_form_builder package
version: 9.0.0
issue_tracker: https://github.com/flutter-form-builder-ecosystem/form_builder_extra_fields/issues
homepage: https://github.com/flutter-form-builder-ecosystem
repository: https://github.com/flutter-form-builder-ecosystem/form_builder_extra_fields
funding:
  - https://opencollective.com/flutter-form-builder-ecosystem

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder:
    git:
      url: https://github.com/vrsct/flutter_form_builder.git
  flutter_colorpicker: ^1.0.3
  dropdown_search: ^5.0.6
  signature: ^5.3.2
  intl: ^0.18.0
  flutter_typeahead: ^4.3.7
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
